# Generated by Django 2.2.10 on 2020-06-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='category')),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='upcomingevent-icons')),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('speakers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='website.Speaker')),
            ],
            options={
                'verbose_name': 'UpcomingEvent',
                'verbose_name_plural': 'UpcomingEvents',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Events')),
                ('title', models.CharField(max_length=50)),
                ('location', models.URLField()),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('buy', models.URLField()),
                ('venue', models.TextField()),
                ('organizer', models.TextField()),
                ('basic_ticket_price', models.IntegerField()),
                ('vip_ticket_price', models.IntegerField()),
                ('number_of_ticket', models.IntegerField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='agendaApp.Category')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='agendaApp.Tag')),
            ],
            options={
                'verbose_name': 'single-event',
                'verbose_name_plural': 'single-events',
            },
        ),
    ]
